version: '3'
services:
  eatitdog:
    image: rddcat/reptile:latest
    ports:
      - 8080:8080
    restart: always
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      AWS_S3_ACCESSKEY: ${AWS_S3_ACCESSKEY}
      AWS_S3_SECRETKEY: ${AWS_S3_SECRETKEY}
      BUCKET_NAME: ${BUCKET_NAME}
      REGION: ${REGION}